### PR TITLE
fix: multiline md with \r\n

### LINKED ISSUE #481: `bundle` command squash referenced markdown file to one string
**Describe the bug**

`bundle` command squash referenced markdown file to one string.
I'm not sure is that a bug or a feature absence 😅 

**To Reproduce**
Given this OpenAPI file:
```yaml
openapi: 3.0.1
info:
  title: Demo API
  version: '1.0'
  description:
    $ref: './description.md'
paths: {}
```

Which has reference to this markdown description:
```markdown
# Heading
List:
- first item
- second item

Line.
Same Line
```

Run this command
```sh
openapi bundle openapi.yaml --output bundled.yaml
```

And look at the squashed description in the bundled file:
```yaml
openapi: 3.0.1
info:
  title: Demo API
  version: '1.0'
  description: "# Heading\r\nList:\r\n- first item\r\n- second item\r\n\r\nLine.\r\nSame Line"
paths: {}
components: {}
```

FYI: swagger-cli have the same behavior

**Expected behavior**
In my opinion it's better not to squash markdown file to single line but to use multiline strings in [literal mode](https://oai.github.io/Documentation/specification-docs.html#providing-long-descriptions-in-yaml).
So the expected bundled file should be:
```yaml
openapi: 3.0.1
info:
  title: Demo API
  version: '1.0'
  description: |
    # Heading
    List:
    - first item
    - second item

    Line.
    Same Line
paths: {}
components: {}
```

**`openapi-cli` Version(s)**
1.0.0-beta.74

**`Node.js` Version(s)**
v16.13.0

### PR DESCRIPTION
**Pull request by iosypov**
## What/Why/How?

Fix #481 . Replace \r\n from source file.

## Check yourself

- [x] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [ ] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

File: packages/core/src/resolve.ts [hunk 1]
```diff
@@ -115,7 +115,9 @@ export class BaseResolver {
         const { body, mimeType } = await readFileFromUrl(absoluteRef, this.config.http);
         return new Source(absoluteRef, body, mimeType);
       } else {
-        return new Source(absoluteRef, await fs.promises.readFile(absoluteRef, 'utf-8'));
+        const content = await fs.promises.readFile(absoluteRef, 'utf-8');
+        // in some cases file have \r\n line delimeters like on windows, we should skip it.
```
Comment (tatomyr) [inline packages/core/src/resolve.ts:119]:
```suggestion
        // In some cases file have \r\n line delimeters like on windows, we should skip it.
```

**Review by tatomyr — APPROVED** [review]
