### PR TITLE
fix: do not remove components which are only used via a reference to a child object

### LINKED ISSUE #1207: remove-unused-components removes components where a child object is referenced
**Describe the bug**

Given an OpenAPI document that contains something along these lines:

```
openapi: "3.0.0"
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Used'
components:
  schemas:
    InnerUsed:
      type: object
      properties:
        link:
          type: string
    Used:
      type: object
      properties:
        link:
          $ref: '#/components/schemas/InnerUsed/properties/link'
```

It would be expected that `bundle --remove-unused-components` would **not** remove the `InnerUsed` schema. It is, in fact, used.

However, the current behavior is that after running `bundle` with `--removed-unused-components`, `InnerUsed` is removed and the resulting document is invalid since the ref can no longer be resolved.

**To Reproduce**

1. Copy the OpenAPI content above to a file.
2. Run `redocly bundle <file.yaml> -o output.yaml --remove-unused-components`
4. Check the output.yaml file.

**Expected behavior**

In this simple case, the input and output should be the same. In a more complex case, _other_ components could be removed, just not this one.

**Logs**

Not applicable.

**OpenAPI definition**

Have only tested with 3.0.

**Redocly Version(s)**

1.0.0 and main.

**`Node.js` Version(s)**

16.17.0, 16.18.0, and 18.16.0

### PR DESCRIPTION
**Pull request by jedelson-pagerduty**
…a child object. fixes #1207

## What/Why/How?

Core problem is described in #1207 

## Reference

Fixes #1207

## Testing

I added a test case for this. I'm not 100% sure that this is the best location for this test but it seemed natural to me.

I've also tested this on a non-trivial OpenAPI document that has dozens of these cases.

## Check yourself

- [X] Code is linted
- [ ] Tested with redoc/reference-docs/workflows *(What does this mean? It's not mentioned in the CONTRIBUTING.md file)*
- [X] All new/updated code is covered with tests

## Security

- [X] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines *(Is this referencing Redocly's security practices?)*

### CODE REVIEW

File: packages/core/src/rules/oas3/remove-unused-components.ts [hunk 1]
```diff
@@ -31,7 +31,11 @@ export const RemoveUnusedComponents: Oas3Rule = () => {
         ) {
           const resolvedRef = resolve(ref);
           if (!resolvedRef.location) return;
-          components.set(resolvedRef.location.absolutePointer, {
+          const outerParts = resolvedRef.location.absolutePointer.split('#', 2);
+          const parts = outerParts[1].split('/').slice(0, 4)
```
Comment (RomanHotsiy) [inline packages/core/src/rules/oas3/remove-unused-components.ts:35]: Also, I would rename variables to clarify the intent to extract only the #/components/schemas/<NAME> part.

Comment (jedelson-pagerduty) [reply packages/core/src/rules/oas3/remove-unused-components.ts]: @RomanHotsiy I've renamed the variables (and moved the `join` up a line).

Question - was this comment meant to be in addition to another comment? Starting with "Also" suggests there's some other feedback but I'm not seeing anything else.

Comment (RomanHotsiy) [reply packages/core/src/rules/oas3/remove-unused-components.ts]: ah, yes, sorry, it was initially but then I edited it out but forgot to remove "also" 😄

**Comment by jedelson-pagerduty** [comment]
@RomanHotsiy can you approve running GitHub actions on this PR? (I assume you can do this) The tests all pass locally but I'd really like to see them passing in CI just to get some extra confidence.

**Comment by RomanHotsiy** [comment]
@jedelson-pagerduty  approved

Performance Benchmark failed due to some permission issue, we can ignore it.

**Comment by tatomyr** [comment]
Hi @jedelson-pagerduty,

We've just updated our publishing process (as well as our [contributing guide](https://github.com/Redocly/redocly-cli/blob/main/.github/CONTRIBUTING.md#pull-request-guidelines)). Could you also add a changeset to your PR? 

Here's the instruction:
 
1. Update your branch with the latest `main`
2. Run `npm i && npx changeset` 
3. Choose to include both packages with a patch bump
4. Provide a short description, e.g. 'Fixed an issue when the `--remove-unused-components` option was removing used components referenced to a child object.'
5. Commit the created file.

Thanks!

**Comment by jedelson-pagerduty** [comment]
@tatomyr that's all done now. thanks for letting me know about the new process.

**Review by tatomyr — APPROVED** [review]

**Comment by tatomyr** [comment]
Feel free to merge. Thanks for your contribution!

**Comment by RomanHotsiy** [comment]
@jedelson-pagerduty we'll merge it tomorrow!

Thanks a lot for your contribution 🙌
