### PR TITLE
fix: add JSON Schema 2019-09+ validation keyword - dependentRequired

### LINKED ISSUE #1558: dependentRequired is valid json schema but does not pass linting and prevents component from being available in UI.
**Describe the bug**

Property `dependentRequired` is not expected here is reported when running the linter. I would expect for an OpenAPI 3.1.0 spec for this to lint and be reflected in the UI generated as it seems to be part of the supported JSON Schema dialect.T

**To Reproduce**

1. Given this `redocly.yaml` file
```
# See https://redocly.com/docs/cli/configuration/ for more information.
extends:
  - recommended 
rules:
  no-unused-components: error
  no-server-example.com: off
  no-empty-servers: off
  security-defined: off
  info-license: off
  operation-4xx-response: off # https://phab.easypo.net/T72078 turn this back on when 4xx are added.
theme:
  openapi:
    htmlTemplate: ./docs/index.html
    theme:
      colors:
        primary:
          main: "#32329f"
    generateCodeSamples:
      languages:  # Array of language config objects; indicates in which languages to generate code samples.
        - lang: curl
```

2. And this OpenAPI file(s) which is using schema example from https://json-schema.org/understanding-json-schema/reference/conditionals#dependentRequired

```
openapi: 3.1.0
info:
  version: 1.0.0
  title: This is only a test.
  description: testing
paths:
  '/test':
    post:
      summary: test use of dependentRequired 
      operationId: test
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  credit_card:
                    type: number
                  billing_address:
                    type: string
                required:
                - name
                dependentRequired:
                  credit_card:
                  - billing_address

```

3. Run this command with these arguments... `redocly ...`
`redocly lint openapi.yaml

6. See error
```
❯ redocly lint openapi.yaml
(node:45032) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
validating openapi.yaml...
[1] openapi.yaml:27:17 at #/paths/~1test/post/responses/200/content/application~1json/schema/dependentRequired

Property `dependentRequired` is not expected here.

25 | required:
26 | - name
27 | dependentRequired:
28 |   credit_card:
29 |   - billing_address

Error was generated by the spec rule.


openapi.yaml: validated in 7ms

❌ Validation failed with 1 error.
run `redocly lint --generate-ignore-file` to add all problems to the ignore file.
```

**Expected behavior**

The lint should pass.

**Logs**

n/a

**OpenAPI description**

Included above.

**Redocly Version(s)**

1.12.2

**`Node.js` Version(s)**

21.6.2

**Additional context**

I have tried to double check that it's not just a formatting error but this looks to be correct according the the json schema doc and is not a linting error when running spectral

### PR DESCRIPTION
**Pull request by jeremyfiel**
fixes #1558

## What/Why/How?
JSON Schema 2019-09 introduced a new validation keyword which applies to OpenAPI 3.1.x support of JSON Schema 2020-12. 

    [6.5.4. ](https://json-schema.org/draft/2020-12/json-schema-validation#section-6.5.4)[dependentRequired](https://json-schema.org/draft/2020-12/json-schema-validation#name-dependentrequired)
    The value of this keyword MUST be an object. Properties in this object, if any, MUST be arrays. Elements in each array, if any, MUST be strings, and MUST be unique.
    
    This keyword specifies properties that are required if a specific other property is present. Their requirement is dependent on the presence of the other property.
    
    Validation succeeds if, for each name that appears in both the instance and as a name within this keyword's value, every item in the corresponding array is also the name of a property in the instance.
    
    Omitting this keyword has the same behavior as an empty object.

## Check yourself

- [ ] Code changed? - Tested with redoc/reference-docs/workflows (internal)
- [ ] All new/updated code is covered with tests
- [ ] New package installed? - Tested in different environments (browser/node)

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

File: packages/core/src/types/oas3_1.ts [hunk 1]
```diff
@@ -134,6 +134,7 @@ const Schema: NodeType = {
     then: 'Schema',
     else: 'Schema',
     dependentSchemas: listOf('Schema'),
+    dependentRequired: mapOf('DependentRequired'),
```
Comment (tatomyr) [inline packages/core/src/types/oas3_1.ts:137]: No need in mapOf, as there are already additionalProperties in the DependentRequired:

```suggestion
    dependentRequired: 'DependentRequired',
```

File: packages/core/src/types/oas3_1.ts [hunk 2]
```diff
@@ -265,6 +266,17 @@ const SecurityScheme: NodeType = {
...
 
+const DependentRequired: NodeType = {
+  properties: {},
+  additionalProperties: (value: any) => {
+    if (Array.isArray(value)) {
+      return { type: 'array', items: { type: 'string'}}
+    } else {
+      return
+    }
+  }
```
Comment (tatomyr) [inline packages/core/src/types/oas3_1.ts:277]: It could be simplified like this:

```suggestion
  additionalProperties: { type: 'array', items: { type: 'string' } },
```

File: .changeset/hungry-bears-do.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@redocly/openapi-core": minor
+---
+
+add JSON Schema draft 2019-09+ validation keyword - dependentRequired
```
Comment (tatomyr) [inline .changeset/hungry-bears-do.md:5]:
```suggestion
"@redocly/openapi-core": patch
---

Added JSON Schema draft 2019-09+ validation keyword - `dependentRequired`.
```

**Review by lornajane — APPROVED** [review]
Changeset is good

File: .changeset/hungry-bears-do.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@redocly/openapi-core": patch
```
Comment (tatomyr) [inline .changeset/hungry-bears-do.md:2]:
```suggestion
"@redocly/openapi-core": patch
"@redocly/cli": patch
```

**Review by tatomyr — APPROVED** [review]
LGTM. Thanks for the contribution!
