### PR TITLE
fix: report component renaming conflicts for same-name components from different files

### LINKED ISSUE #2691: bundle with --component-renaming-conflicts-severity ignored the reference
**Describe the bug**
`--component-renaming-conflicts-severity` seems only flag file reference but not pointer reference.

**To Reproduce**

1. Set up `openapi.yaml` like following

```yaml
openapi: 3.1.0
paths:
  /foo:
    put:
      parameters:
        - $ref: 'A.yaml#/components/parameters/User'
    get:
      parameters:
        - $ref: 'B.yaml#/components/parameters/User'

```

2. Set up `A.yaml` and `B.yaml` with slightly different specs
- A.yaml
```yaml
components:
  parameters:
    User:
      name: test
      in: path
      description: test-A
```

- B.yaml
```yaml
components:
  parameters:
    User:
      name: test
      in: query
      description: test-B
```

**Expected behavior**

When run `redocly bundle index.yaml --component-renaming-conflicts-severity=error`, I would expect it to fail, as both `User` are conflicts in naming, but it went through without errors.

**Logs**

```
bundling index.yaml...
openapi: 3.1.0
paths:
  /foo:
    put:
      parameters:
        - $ref: '#/components/parameters/parameters-User'
    get:
      parameters:
        - $ref: '#/components/parameters/User'
components:
  parameters:
    User:
      name: test
      in: query
      description: test-B
    parameters-User:
      name: test
      in: path
      description: test-A
📦 Created a bundle for index.yaml at stdout 9ms.
```

**Redocly version(s)**

2.25.1

**Node.js version(s)**

Node v24.3.0
NPM 11.4.2

**OS, environment**

Mac M1

**Additional context**

### PR DESCRIPTION
**Pull request by kanoru3101**
## What/Why/How?
The `bundle` command now reports component renaming conflicts whenever two external definitions share the **same name** but have **different** content. 

Also, another issue was that we created two types of uniq names. For `pointer` - it was with `prefix`, and for other cases was `suffix`

Removed logic to create [prefix](https://github.com/Redocly/redocly-cli/pull/181) for the component name when the component name has the same name

[Tested](https://github.com/Redocly/redocly/pull/22247) with other products

## Reference
close #2691
### Without `--component-renaming-conflicts-severity` rule

Screenshot 2026-04-06 at 19 53 19

### With `--component-renaming-conflicts-severity=error` rule

Screenshot 2026-04-06 at 19 53 49

### With `--component-renaming-conflicts-severity=warn` rule

Screenshot 2026-04-06 at 19 54 21

### With `--component-renaming-conflicts-severity=off` rule

Screenshot 2026-04-06 at 19 54 51

## Check yourself

- [x] Code changed? - Tested with Redoc/Realm/Reunite (internal)
- [x] All new/updated code is covered by tests
- [ ] New package installed? - Tested in different environments (browser/node)
- [x] Documentation update considered

## Security

- [x] The security impact of the change has been considered
- [x] Code follows company security practices and guidelines

---

> [!NOTE]
> **Medium Risk**
> Changes bundling component naming and conflict detection, which can alter generated component names and `$ref` paths in bundled outputs. Risk is moderate due to potential breaking snapshot/output diffs for consumers relying on stable bundled names.
> 
> **Overview**
> Bundling now **detects and reports component renaming conflicts** when external components share the same name but have different content, honoring `--component-renaming-conflicts-severity` for these cases.
> 
> Component name generation was simplified to derive names from the JSON pointer basename (falling back to the file basename) and then apply a consistent `-2`, `-3`, … suffix for conflicts; this changes some autogen component keys and resulting `$ref` targets.
> 
> Tests and fixtures were updated/added to cover pointer-based external refs conflicts and ensure dotted schema keys (e.g. `my.org.User`) are preserved, and snapshots were updated to reflect the new naming/warning behavior.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit cf50a5bf4fd6e955603c09646e8cd129a5f66f29. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: packages/core/src/bundle/bundle-visitor.ts [hunk 1]
```diff
@@ -287,15 +298,19 @@ export function makeBundleVisitor({
         !componentsGroup[name] ||
         isEqualOrEqualRef(componentsGroup[name], target, ctx)
       ) {
+        reportIfRenamed(renameSource, name, ctx);
         return name;
       }
+      renameSource ||= name;
```
Comment (kanoru3101) [inline packages/core/src/bundle/bundle-visitor.ts]: It's the same as `renameSource = renameSource || name` or
```
if (!renameSource) {
  renameSource = name;
}
```

File: .changeset/quiet-snakes-buy.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+"@redocly/openapi-core": patch
+"@redocly/cli": patch
+---
+
+Fixed `--component-renaming-conflicts-severity` ignoring conflicts when different files have components with the same name but different content.
```
Comment (JLekawa) [inline .changeset/quiet-snakes-buy.md]:
```suggestion
Fixed an issue where `--component-renaming-conflicts-severity` ignored conflicts when different files had components with the same name but different content.
```

**Review by JLekawa — APPROVED** [review]

File: packages/core/src/__tests__/bundle.test.ts [hunk 3]
```diff
@@ -119,6 +123,50 @@ describe('bundle', () => {
...
+      ref: path.join(
+        __dirname,
+        'fixtures/refs/openapi-with-external-refs-pointer-conflicting-names.yaml'
+      ),
+      componentRenamingConflicts: 'off',
+    });
+    expect(problems).toHaveLength(0);
+  });
+
+  it('should bundle external pointer refs and show errors for conflicting names', async () => {
```
Comment (tatomyr) [inline packages/core/src/__tests__/bundle.test.ts]: The description seems misleading. Will this produce the bundle at all?

**Review by tatomyr — COMMENTED** [review]
The issue here is that the bundler doesn't apply renaming consistently. If the schema wasn't referenced with a JSON pointer inside the file, it would behave correctly.

File: packages/core/src/__tests__/bundle.test.ts (hunk 3 above)
Comment (kanoru3101) [reply packages/core/src/__tests__/bundle.test.ts]: The description has been updated. Yes, if an error occurs, the build should not proceed.

File: packages/core/src/bundle/bundle-visitor.ts [hunk 4]
```diff
@@ -274,27 +274,9 @@ export function makeBundleVisitor({
...
-
-    const refParts = pointer.slice(2).split('/').filter(isTruthy); // slice(2) removes "#/"
-    while (refParts.length > 0) {
-      name = refParts.pop() + (name ? `-${name}` : '');
-      if (
-        !componentsGroup ||
-        !componentsGroup[name] ||
-        isEqualOrEqualRef(componentsGroup[name], target, ctx)
-      ) {
-        return name;
```
[the remark this answers is not in the document]
Comment (kanoru3101) [reply packages/core/src/bundle/bundle-visitor.ts:290]: it was removed

File: packages/core/src/ref-utils.ts [hunk 5]
```diff
@@ -76,7 +76,7 @@ export function parsePointer(pointer: string) {
 
 export function pointerBaseName(pointer: string) {
   const parts = pointer.split('/');
-  return parts[parts.length - 1];
+  return unescapePointerFragment(parts[parts.length - 1]);
```
[the remark this answers is not in the document]
Comment (kanoru3101) [reply packages/core/src/ref-utils.ts]: This looks like a bug, but it's safe — the [OAS](https://spec.openapis.org/oas/v3.2.0.html#components-object) spec only allows `^[a-zA-Z0-9\.\-_]+$` as component keys, so `/` and `~` are not supported in valid names.

File: packages/core/src/bundle/bundle-visitor.ts [hunk 6]
```diff
@@ -303,7 +285,7 @@ export function makeBundleVisitor({
       serialId++;
     }
 
-    if (!componentsGroup[name]) {
+    if (!componentsGroup[name] && prevName !== name) {
```
Comment (tatomyr) [inline packages/core/src/bundle/bundle-visitor.ts:288]:
```suggestion
    if (  prevName !== name) {
```

De we need the first part?

File: packages/core/src/ref-utils.ts (hunk 5 above)
Comment (tatomyr) [inline packages/core/src/ref-utils.ts]: Could you explain why do we need to unescape the pointer fragment.

File: packages/core/src/bundle/bundle-visitor.ts (hunk 6 above)
Comment (kanoru3101) [reply packages/core/src/bundle/bundle-visitor.ts:288]: Yes, I found the case when we needed it. The `!componentsGroup[name]` check is needed because `prevName !== name` alone would also `warn` when the renamed component already exists with the same content — which is not a conflict.

Example from test:
```yaml
openapi: 3.1.0
info:
  title: My API
  description: It ain't so wonderful, but at least it's mine.
  version: '1.0'
  contact:
    email: me@theintenet.com
    name: me
paths:
  /test:
    get:
      summary: 'test'
      responses:
        200:
          description: test
          content:
            application/json:
              schema:
                $ref: ./vendor.schema.yaml
components:
  schemas:
    vendor:
      $ref: ./vendor.schema.yaml
    myvendor:
      $ref: ./vendor.schema.yaml
    simple:
      $ref: ./simple.yaml
    A:
      $ref: ./definitions.yaml#/$defs/A
    test:
      $ref: ./rename.yaml
    rename:
      type: string
    rename-2:        
      $ref: ./rename.yaml
```

```yaml
// rename.yaml
type: number
```

and after building it will be 
```yaml
openapi: 3.1.0
...
components:
    ...
    test:
      $ref: '#/components/schemas/rename-2'
    rename:
      type: string
    rename-2:
      type: number
    ...
```

That makes sense, doesn't it?

File: packages/core/src/ref-utils.ts (hunk 5 above)
Comment (kanoru3101) [reply packages/core/src/ref-utils.ts]: Removed

[the remark this answers is not in the document]
Comment (kanoru3101) [reply packages/core/src/ref-utils.ts]: Removed

File: packages/core/src/bundle/bundle-visitor.ts (hunk 6 above)
Comment (tatomyr) [reply packages/core/src/bundle/bundle-visitor.ts:288]: Is there a test covering that?

Comment (kanoru3101) [reply packages/core/src/bundle/bundle-visitor.ts:288]: Yes, I discovered it when I run test

**Review by tatomyr — APPROVED** [review]

File: .changeset/quiet-snakes-buy.md [hunk 7]
```diff
@@ -0,0 +1,8 @@
+---
+"@redocly/openapi-core": patch
+"@redocly/cli": patch
+---
+
+Fixed an issue where `--component-renaming-conflicts-severity` ignored conflicts when different files had components with the same name but different content.
+
+**Warning:** Bundled `$ref` paths may differ from older releases.
```
Comment (tatomyr) [inline .changeset/quiet-snakes-buy.md]: Let's do something like this:

```suggestion
**Warning:** Autogenrated component names and `$ref` paths in bundled documents may differ from older releases.
```

cc @JLekawa

**Review by JLekawa — APPROVED** [review]
