### PR TITLE
OAS3_1 types `SchemaProperties` updated per JSON Schema draft 2020-12

### LINKED ISSUE #1296: Lint error: Expected type `Schema` (object) but got `boolean` appears when linting API definition
**Describe the bug**

Upon linting a valid API Definition, the error message "Expected type `Schema` (object) but got `boolean`" appears

**To Reproduce**

1. Given this `redocly.yaml` file:
[redocly.yaml.zip](https://github.com/Redocly/redocly-cli/files/12884924/redocly.yaml.zip)

2. And this OpenAPI file
[openapi.yaml.zip](https://github.com/Redocly/redocly-cli/files/12884941/openapi.yaml.zip)

3. Run this command: redocly lint openapi.yaml
4. See error: Expected type `Schema` (object) but got `boolean`

**Expected behavior**

In accordance with JSON Schema documentation: 
https://json-schema.org/understanding-json-schema/reference/object#extending, in order to extend closed schemas you can write your schema as in the example below: 

```yaml

components:
  schemas:
    MyObject:
      type: object
      additionalProperties: false
      allOf:
        - $ref: '#/components/schemas/MyObjectBase'
      properties:
        property1: true
        property2: true 
      required:
        - property2
    MyObjectBase:
      type: object
      properties:
        property1:
          type: string
        property2:
          type: string
      required:
        - property1
       
```

However,  it seems Redocly CLI does not cover this use case since the error message occurs:

        
Screenshot 2023-10-12 at 19 40 55

Front logo [Front conversations](https://app.frontapp.com/open/top_25dido)

### PR DESCRIPTION
**Pull request by jeremyfiel**
## What/Why/How?

OpenAPI 3.1.x defaults to JSON Schema draft 2020-12 and the value of property names defined in `properties` was updated since OpenAPI 3.0.x and JSON Schema draft-04. 

In the new JSON Schema specification, each property value within a `properties` schema accepts a `boolean` or `object` schema.

fixes #1296 

## Reference
https://json-schema.org/draft/2020-12/json-schema-core#section-10.3.2.1
## Check yourself

- [x] Code is linted
- [ ] Tested with redoc/reference-docs/workflows (internal)
- [ ] All new/updated code is covered with tests

## Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### CODE REVIEW

**Comment by jeremyfiel** [comment]
It seems like the failing tests are unrelated to my changes.  I could be wrong though  lol

**Review by RomanHotsiy — APPROVED** [review]

**Comment by tatomyr** [comment]
@jeremyfiel thanks for opening the PR! I'll look into the failing tests tomorrow.

File: packages/core/src/types/oas3_1.ts [hunk 1]
```diff
@@ -181,6 +181,18 @@ const Schema: NodeType = {
...
+const SchemaProperties: NodeType = {
+  properties: {
+    propertyName: (value: any) => {
+      if (typeof value === 'boolean') {
+        return { type: 'boolean' };
+      } else {
+        return 'Schema';
+      }
+    },
+  },
```
Comment (tatomyr) [inline packages/core/src/types/oas3_1.ts:193]: I'm not 💯 sure, but it looks like it should be this way:

```suggestion
  properties: {},
  additionalProperties: (value) => {
      if (typeof value === 'boolean') {
        return { type: 'boolean' };
      } else {
        return 'Schema';
      }
  },
```

Could you check if that works better?

Comment (jeremyfiel) [reply packages/core/src/types/oas3_1.ts:193]: how can I run the smoke tests locally?  if i run jest, the tests pass.

Do I need to commit the updated snapshots for the `build and test` command to pass?

```shell
Snapshot Summary
 › 270 snapshots updated from 60 test suites.

Test Suites: 1 skipped, 93 passed, 93 of 94 total
Tests:       2 skipped, 640 passed, 642 total
Snapshots:   270 updated, 84 passed, 354 total
Time:        47.02 s
```

Comment (jeremyfiel) [reply packages/core/src/types/oas3_1.ts]: @tatomyr  i fixed it per your suggestion.  ok to merge now if you agree with the changes. thanks for the help!
