### PR TITLE
fix: run-id parameter is not working properly

### LINKED ISSUE #721: run-id parameter is not working properly
**Describe the bug**
The `--run-id` [parameter](https://redocly.com/docs/cli/commands/push/#run-id) is not sent to the server.

**To Reproduce**
Do the `push` command with `--run-id` parameter, notice that the parameter is not used. (check the source code)

**Expected behavior**
The `--run-id` parameter should works as described in [the command docs](https://redocly.com/docs/cli/commands/push/#run-id)

**Logs**
If applicable, add logs to help explain your problem.

**OpenAPI definition**
-

**Redocly Version(s)**
What version of Redocly CLI are you using?
`1.0.0-beta.100`

**`Node.js` Version(s)**
What version of `node.js` are you using?
any

**Additional context**

### PR DESCRIPTION
**Pull request by AntonKozachuk**
## What/Why/How?
Resolve an issue with the 'run-id' parameter not working properly.

## Reference
Closes #721

## Check yourself

- [x] Code is linted
- [ ] Tested with redoc/reference-docs/workflows
- [x] All new/updated code is covered with tests

## Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Review by SmoliyY — APPROVED** [review]

**Review by RomanHotsiy — COMMENTED** [review]
LGTM 👍

File: packages/cli/src/commands/push.ts [hunk 1]
```diff
@@ -82,6 +86,18 @@ export async function handlePush(argv: PushArgs): Promise<void> {
     );
   }
 
+  if (batchId && !batchId.replace(/\s/g, '')) {
```
Comment (SmoliyY) [inline packages/cli/src/commands/push.ts:89]: Maybe it can be simplified to !batachId.trim() ?

Comment (AntonKozachuk) [reply packages/cli/src/commands/push.ts]: Make sense. Added.
